# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0040_remove_projects_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='Team_Members',
        ),
    ]
