# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0041_remove_projects_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Progress',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Team_Members',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
